name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-test
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3

      - name: Setup JS dependencies
        uses: ./.github/workflows/setup-pnpm
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}

      - name: Run tests
        run: pnpm test:jest
